" ~/.vimrc
"
" @package myutilitybelt
" @subpackage vim
" @author thiagoalessio <thiagoalessio@me.com>

" general settings
source ~/.myutilitybelt/vim/general.vim

" using Vundle to manage plugins
" see: https://github.com/gmarik/Vundle.vim
source ~/.myutilitybelt/vim/vundle.vim

"key mappings
"source ~/.vim/mappings.vim
"""source ~/.vim/dvorak.vim

"file browsing
"source ~/.vim/ctrlp.vim
"source ~/.vim/nerdtree.vim

"code editing
"source ~/.vim/easymotion.vim
"source ~/.vim/folding.vim
source ~/.myutilitybelt/vim/indentation.vim
"source ~/.vim/syntastic.vim
"source ~/.vim/tabular.vim
"source ~/.vim/undotree.vim

"integration
"source ~/.vim/vimux.vim

"vim interface
source ~/.myutilitybelt/vim/interface.vim
"source ~/.vim/search.vim

"visual/fancy stuff
"source ~/.vim/airline.vim
"source ~/.vim/colors.vim
