# ~/.zshrc
#
# @package myutilitybelt
# @subpackage zsh
# @author thiagoalessio <thiagoalessio@me.com>
# @author Victor Schröder <schrodervictor@gmail.com>

source ~/.myutilitybelt/zsh/private.zsh

source ~/.myutilitybelt/zsh/aliases.zsh
source ~/.myutilitybelt/zsh/colors.zsh
source ~/.myutilitybelt/zsh/completion.zsh
source ~/.myutilitybelt/zsh/environment.zsh
source ~/.myutilitybelt/zsh/history.zsh
source ~/.myutilitybelt/zsh/log.zsh
source ~/.myutilitybelt/zsh/prompt.zsh
source ~/.myutilitybelt/zsh/tmux.zsh
source ~/.myutilitybelt/zsh/vcs.zsh
source ~/.myutilitybelt/zsh/github.zsh
source ~/.myutilitybelt/zsh/emacs-mode.zsh
source ~/.myutilitybelt/zsh/nvm.zsh
source ~/.myutilitybelt/zsh/ansible.zsh
source ~/.myutilitybelt/zsh/rvm.zsh
source ~/.myutilitybelt/zsh/mongodb-atlas.zsh

source ~/.myutilitybelt/aws/profile-manager.zsh

GCP_SDK_HOME='/opt/google/gcp-sdk/google-cloud-sdk-450.0.0'
# The next line updates PATH for the Google Cloud SDK.
if [ -f "$GCP_SDK_HOME/path.zsh.inc" ]; then
    . "$GCP_SDK_HOME/path.zsh.inc"
fi
# The next line enables shell command completion for gcloud.
if [ -f "$GCP_SDK_HOME/completion.zsh.inc" ]; then
    . "$GCP_SDK_HOME/completion.zsh.inc"
fi
